Vagrant.configure("2") do |config|

  # Define the Ubuntu VM named 'web'
  config.vm.define "ubuntu" do |vm|
    vm.vm.box = "ubuntu/bionic64"
    vm.vm.network "private_network", ip: "192.168.33.10"
    vm.vm.hostname = "ubuntu"
  end

  # Define the Ubuntu VM named 'spider'
  config.vm.define "ubuntu2" do |vm|
    vm.vm.box = "ubuntu/bionic64"
    vm.vm.network "private_network", ip: "192.168.33.11"
    vm.vm.hostname = "ubuntu2"
  end

  # Define the CentOS VM
  config.vm.define "centos" do |vm|
    vm.vm.box = "centos/7"
    vm.vm.network "private_network", ip: "192.168.33.20"
    vm.vm.hostname = "centos"
  end
end